//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDSPMapInserter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BDSPMapInserter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;ID&quot;: 0,
        ///    &quot;AreaName&quot;: &quot;C01&quot;,
        ///    &quot;FriendlyName&quot;: &quot;&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;ID&quot;: 1,
        ///    &quot;AreaName&quot;: &quot;C01FS0101&quot;,
        ///    &quot;FriendlyName&quot;: &quot;&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;ID&quot;: 2,
        ///    &quot;AreaName&quot;: &quot;C01PC0101&quot;,
        ///    &quot;FriendlyName&quot;: &quot;&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;ID&quot;: 3,
        ///    &quot;AreaName&quot;: &quot;C01PC0102&quot;,
        ///    &quot;FriendlyName&quot;: &quot;&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;ID&quot;: 4,
        ///    &quot;AreaName&quot;: &quot;C01PC0103&quot;,
        ///    &quot;FriendlyName&quot;: &quot;&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string area_id {
            get {
                return ResourceManager.GetString("area_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;script-data&quot;: {
        ///		&quot;key&quot;: &quot;script-data&quot;,
        ///		&quot;file_name&quot;: &quot;ev_script&quot;,
        ///		&quot;full_path&quot;: &quot;Data\\StreamingAssets\\AssetAssistant\\Dpr\\ev_script&quot;,
        ///		&quot;cab_directory&quot;: &quot;CAB-e856180fe48cd419c06715341f9e3f42&quot;,
        ///		&quot;files&quot;: [
        ///			&quot;debug&quot;
        ///		]
        ///	},
        ///	&quot;dpr-masterdatas&quot;: {
        ///		&quot;key&quot;: &quot;dpr-masterdatas&quot;,
        ///		&quot;file_name&quot;: &quot;masterdatas&quot;,
        ///		&quot;full_path&quot;: &quot;Data\\StreamingAssets\\AssetAssistant\\Dpr\\masterdatas&quot;,
        ///		&quot;cab_directory&quot;: &quot;CAB-9dc85906fd5b2461ef3e4f7cfebad93c&quot;,
        ///		&quot;files&quot;: [
        ///			&quot;MapWarp_A01&quot;,
        ///			&quot;PlaceData_A0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bundle_constants {
            get {
                return ResourceManager.GetString("bundle_constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sinnoh {
            get {
                object obj = ResourceManager.GetObject("sinnoh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon sinnoh_ico {
            get {
                object obj = ResourceManager.GetObject("sinnoh_ico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string str_length {
            get {
                return ResourceManager.GetString("str_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;ID&quot;: 0,
        ///    &quot;ZoneName&quot;: &quot;C01&quot;,
        ///    &quot;FriendlyName&quot;: &quot;&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;ID&quot;: 1,
        ///    &quot;ZoneName&quot;: &quot;C01FS0101&quot;,
        ///    &quot;FriendlyName&quot;: &quot;&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;ID&quot;: 2,
        ///    &quot;ZoneName&quot;: &quot;C01PC0101&quot;,
        ///    &quot;FriendlyName&quot;: &quot;&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;ID&quot;: 3,
        ///    &quot;ZoneName&quot;: &quot;C01PC0102&quot;,
        ///    &quot;FriendlyName&quot;: &quot;&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;ID&quot;: 4,
        ///    &quot;ZoneName&quot;: &quot;C01PC0103&quot;,
        ///    &quot;FriendlyName&quot;: &quot;&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zone_id {
            get {
                return ResourceManager.GetString("zone_id", resourceCulture);
            }
        }
    }
}
