//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDSPMapInserter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BDSPMapInserter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;PathID&quot;: -4159401333858848265,
        ///    &quot;FileName&quot;: &quot;battle_room&quot;,
        ///    &quot;FriendlyName&quot;: &quot;Unused Wireless Battle Room (?)&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;PathID&quot;: -594893302899321786,
        ///    &quot;FileName&quot;: &quot;bg_attr&quot;,
        ///    &quot;FriendlyName&quot;: &quot;Tile-specific Scripts&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;PathID&quot;: -524791092379703435,
        ///    &quot;FileName&quot;: &quot;c01&quot;,
        ///    &quot;FriendlyName&quot;: &quot;Jubilife City&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;PathID&quot;: -696005077699342123,
        ///    &quot;FileName&quot;: &quot;c01fs0101&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string area_id {
            get {
                return ResourceManager.GetString("area_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;script-data&quot;: {
        ///		&quot;key&quot;: &quot;script-data&quot;,
        ///		&quot;file_name&quot;: &quot;ev_script&quot;,
        ///		&quot;full_path&quot;: &quot;Data\\StreamingAssets\\AssetAssistant\\Dpr\\ev_script&quot;,
        ///		&quot;cab_directory&quot;: &quot;CAB-e856180fe48cd419c06715341f9e3f42&quot;,
        ///		&quot;files&quot;: [
        ///			&quot;trainer&quot;
        ///		]
        ///	}
        ///}.
        /// </summary>
        internal static string bundle_constants {
            get {
                return ResourceManager.GetString("bundle_constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;PathID&quot;: -4159401333858848265,
        ///    &quot;FileName&quot;: &quot;battle_room&quot;,
        ///    &quot;FriendlyName&quot;: &quot;Unused Wireless Battle Room (?)&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;PathID&quot;: -594893302899321786,
        ///    &quot;FileName&quot;: &quot;bg_attr&quot;,
        ///    &quot;FriendlyName&quot;: &quot;Tile-specific Scripts&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;PathID&quot;: -524791092379703435,
        ///    &quot;FileName&quot;: &quot;c01&quot;,
        ///    &quot;FriendlyName&quot;: &quot;Jubilife City&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;PathID&quot;: -696005077699342123,
        ///    &quot;FileName&quot;: &quot;c01fs0101&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zone_id {
            get {
                return ResourceManager.GetString("zone_id", resourceCulture);
            }
        }
    }
}
